### ISSUE TITLE
Thoughts on overall concept of promises in IDB

### ISSUE THREAD

**Issue by nolanlawson** [inexorabletash/indexeddb-promises#12]
During the f2f yesterday ([transcript](https://www.w3.org/2016/09/23-webapps-minutes.html#item03)) I gave some feedback that may have come across as flippant or harsh, so I'd like to clarify my thinking on this a bit more.

In general I'm uneasy about the idea of bolting-on a promise API to the existing IDB API, because I don't believe it will solve the problems of the people who just want "promises in IDB." What I think most web developers really want is "async localStorage," as evidenced by stuff like localForage, idb-keyval, indexeddb-promised, etc.

In contrast, the proposed API not only contains some footguns (e.g. [the need for `waitUntil()` to work around auto-committing transactions](https://github.com/inexorabletash/indexeddb-promises#advanced-usage), the question of how to elegantly handle ConstraintErrors (#6)), but will also probably dissatisfy the "async localStorage" crowd because they still have to deal with `onupgradeneeded`, transactions, cursors, etc.

My proposal: IndexedDB needs a "simple" API for folks who miss `localStorage`, but the original IDB API should go lower-level, for those of us who are building databases on top of it. The current API is low-level enough to be annoying to casual developers, while still high-level enough to frustrate advanced devs who just want ["leveldb in the browser"](https://twitter.com/substack/status/577768318502707200).

So for the **low-level folks** (e.g. me :wink:), I say keep doing what you're doing. IDB v2 is great, Observables are also great, `putAll()`/`addAll()` would be a nice addition (coalescing ConstraintErrors I suppose?), maybe also letting us control our own transactions would be nice (e.g. for the "FileReader in a transaction" case), but putting promises on top is not super helpful to us, because we're already writing libraries that expose promises.

Now for the **high-level folks**, create a new API (call it `indexedDB.openLite()`, I dunno), and do something based off your design linked from https://github.com/w3c/IndexedDB/issues/91, e.g.
- no transactions
- no upgrades
- no secondary indexes
- no cursors

Data can live alongside existing IDB databases. A "simple" DB can never be upgraded to a regular one (because Keep It Simple&trade;). Every API call is its own transaction, readonly/readwrite per intent, and returns promises. E.g.:
- `put()`
- `get()`
- `has()`
- `keys()`
- `size()`
- `putAll()` (no need for ConstraintErrors because no secondary indexes)
- `getAll()` (pass in an IDBKeyRange, get back an array. users can build their own pagination if they want _(**edit:** may need limit/offset as well to accomplish this)_)

This is just a sketch of an idea, but I wanted to get these ideas out to make it clear that I really do have feedback to contribute, and wasn't just grouching. 😅 

/cc @aliams @daleharvey @tofumatt @yathit @jakearchibald

**Comment by dumbmatter** [comment]
[This](https://github.com/dfahlander/Dexie.js/issues/317) is the biggest problem for low-level folks, IMHO. If all other browsers could be changed to behave like Chrome, then it'd be easy to make libraries that expose promises. Otherwise, it's fraught with peril. Is it easier to get other browsers to change how transactions commit, or get them to implement another API to explicitly support promises? I don't know, and as a consumer of the IDB API, I don't really care. I just care that the status quo (if you use IDB+promises, you need hacks and even then cross-browser support is a persistent concern) is not good.

**Comment by tofumatt** [comment]
I can't think of much to add, but I agree with everything.

Adding Promises directly to IndexedDB wouldn't matter a great deal to me. It's relatively easy to add Promises to any API wrapper, which IndexedDB warrants use with (again, as evidenced by the popularity of third-party wrappers). If Promises were added... I might rely on them when localForage ditches callbacks (eventually), but otherwise it doesn't matter much.

For most users, yeah, a simple solution like @nolanlawson mentioned (essentially the localForage API methods) with a simple DB (no versioning, etc.) would _massively_ benefit most developers and mean they wouldn't need to include something like localForage for simple get/set calls.

I suppose if the simple API (IDBLite™) were implemented, Promises would matter more and be worth implementing.

**Comment by nolanlawson** [comment]
@dumbmatter I read through #317, but my understanding is that it's a feature, not a bug, that IDB transactions auto-commit when you yield to a microtask (otherwise e.g. a `fetch()` could indefinitely hang transactions). @inexorabletash works around this with `waitUntil()` in this repo.

IDB has lots of cross-browser bugs, but hopefully we can fix that at the vendor level (and hey I'm on the Edge team now... yay :D), whereas my worry with this proposal is introducing new APIs that don't really solve the underlying problems.

+1 to what @tofumatt said about basically just standardizing LocalForage... it's proven to be popular, it has promises, so just give the people what they want. :) My only addition would be the bulk APIs.

**Comment by dumbmatter** [comment]
https://bugs.chromium.org/p/chromium/issues/detail?id=457409 says:

> FWIW, neither FF nor Chrome - nor the spec - have intentional behavior here; the implementations and spec predate microtasks, so the behavior "falls out" differently in different places.

Regardless, my point is just that this is a really important issue for people making intensive use of IDB. My apologies if that's already clear to everyone :)

**Comment by dfahlander** [comment]
@nolanlawson I don't think fetch() will hang indexedDB transactions because it actually does an async operation and not just another micro-tick. Need to distinguish two separate issues:
1. IndexedDB transactions + Promise microticks = not working
2. IndexedDB transactions + non-IDB async operations = not working.

The first one is the most critical and fixing it will not expose the risk of hanging transactions more than what a while(true) loop would. Chromium shows us how this can be implemented.

The second one would probably also be beneficial for dealing with transactions during non-IDB asynchronous operations, but the area is more complex and not that critical as the first one.

**Comment by nolanlawson** [comment]
I'm not entirely sure that the Chromium implementation solves many practical issues. For me, being able to suspend transactions on arbitrary async operations (e.g. `fetch()`, `FileReader`) is more useful. (It's one of the things I like in this proposal; `waitUntil()` gives library authors a tool to control transactions).

This probably isn't the forum for that discussion, though; may be worth bringing up at https://github.com/w3c/indexeddb if it's not already covered. (Maybe it's under-specced and that's why browsers diverge?)

**Comment by dfahlander** [comment]
For sure, waitUntil () solves both issues. I like it. 

_EDIT: It actually solves the second issue. As I understand this proposal, the first issue should be solved without having to call waitUntil()_

**Comment by jakearchibald** [comment]
I'm a little confused by the overall argument in this thread. It seems to be:

> We don't need promises, they can be added pretty easily by a library

…but then…

> What we really need is an async key-val store

…which is [_even easier_ to do as a library](https://www.npmjs.com/package/idb-keyval).

I threw together idb-keyval as people were asking for it, but I find I quickly outgrow it in my own projects. Eg, I'll want to represent an "outbox", and doing that as `{"outbox": […]}` is really risky when it comes to removing/adding a single item.

**Comment by jakearchibald** [comment]
@nolanlawson 

> I'm not entirely sure that the Chromium implementation solves many practical issues

You can't properly promisify IDB without it. With https://www.npmjs.com/package/idb:

``` js
const tx = db.transaction('store', 'readwrite');
const store = tx.objectStore('store');
store.get('hello').then(val => store.put(val, 'foo'));
```

How the above _should_ happen:
1. Transaction open
2. `get('hello')`
3. Library catches `onsuccess` and resolves a promise with `val`
4. Event dispatch ends
5. Microtask checkpoint - promise handlers called
6. `put(val, 'foo')`
7. Library catches `onsuccess` and resolves a promise with undefined
8. Microtask checkpoint - promise handlers called
9. Transaction closes

But here's what happens outside Chromium:
1. Transaction open
2. `get('hello')`
3. Library catches `onsuccess` and resolves a promise with `val`
4. Event dispatch ends
5. **Transaction closes**
6. Microtask checkpoint - promise handlers called
7. `put(val, 'foo')`
8. **Put fails, transaction has closed**

Other browsers do this in error. Dispatching the `success` event involves calling callbacks, and calling callbacks should perform a microtask checkpoint if the JS stack is empty.

**Comment by jakearchibald** [comment]
I've been thinking a little more about this. Here's some code written with [idb-keyval](https://www.npmjs.com/package/idb-keyval).

``` js
idbKeyval.get('counter').then(val => idbKeyval.set('counter', val++));
```

The above code is unsafe:
1. "counter" is 1
2. Window reads "counter" as 1
3. Worker reads "counter" as 1
4. Window sets "counter" as 2
5. Worker sets "counter" as 2

Two increments end up being one. Are we happy adding an API that has this problem?

**Comment by nolanlawson** [comment]
@jakearchibald Yeah my idea with this was that it wouldn't be used with mission-critical stuff where you need transactions/locking. Definitely this API would have this problem, but it's still better than LocalStorage. ¯\_(ツ)_/¯

As for the Chromium ordering issue: yeah, other browsers should fix this.

As for your point about how idb-keyval is easy to do as a library, that's a good point. Maybe it would argue, then, that we don't need to add promises to IDB at all. The only reason I thought to propose a new API is that there seem to be folks who are allergic to libraries and just want to use raw browser APIs (e.g. note how popular `fetch()` is). Also isn't that the extensible web manifesto? We write low-level APIs, someone writes a polyfill that's super popular, and then we enshrine it as a browser API?

**Comment by jakearchibald** [comment]
@nolanlawson 

> The only reason I thought to propose a new API is that there seem to be folks who are allergic to libraries and just want to use raw browser APIs (e.g. note how popular fetch() is). Also isn't that the extensible web manifesto?

Agreed. I think a lot of people avoid IDB because of the awful API, even though the awful API can be solved by a small library. That's why I support making promises work here.

As for a smaller key-val store, I'm open to it, but an API that isn't transactionally safe sounds a bit risky. Could be fixed by having methods like `asyncStore.update(keys, currentValues => newValues)` or something.

**Comment by indolering** [comment]
Disclaimer: this is a poorly informed opinion (I'm not a DB expert) but I thought an outsider perspective might be helpful 😅 

I'm frustrated with IndexedDB, but the syntax proposed here feels like you are trying to shoehorn transaction semantics into promises and await.  What's proposed here makes it so I have to reason about how IndexedDB works and your new extensions to Promises at the same time.

If that makes it easier to write a high-level interface for IndexedDB, then I'm all for it.  But most of the examples in the proposal and in this thread look non-sensical to an outsider.  I disagree with Nolan that a simple async key/value store would suffice (transactions are a must) but I do agree with the overall strategy.

**Comment by nolanlawson** [comment]
Hm, if our goal is to provide an API that is:

- promisey
- attractive to developers
- can outgrow simple uses like `idb-keyval`

then maybe we should take another look at [rdb](https://arthurhsu.github.io/rdb/)? :smiley:

For the question of promises-in-indexeddb, though, I think I'd circle back to my main points:

1. **Library authors probably won't use it.** In Pouch we've already done the workarounds to do `FileReader` outside of the transaction, can't think of anywhere we'd use this API. The only case I can imagine using it would be to break up a large transaction into smaller chunks (e.g. with `requestIdleCallback`) to avoid blocking, but in those cases I would recommend using a web worker anyway. As @tofumatt said re: LocalForage, "wouldn't matter a great deal," I can concur based on on what I've seen of the LF codebase, simple enough to just wrap Promises around transaction callbacks. And as @dumbmatter said, I would also worry about backwards compat; if you have to support non-Promise IDB implementations anyway, then you might as well only use the non-Promise APIs.
2. **Average web devs probably won't use it**. Libraries still offer more attractive API surfaces, and all of them have promises already. The proposed API is still way less ergonomic than something like Dexie or LocalForage (or the hypothetical AsyncLocalStorage).

**Comment by dumbmatter** [comment]
I'll circle back too then :)

You might as well only use the non-Promise APIs... if all non-Chrome browsers switch to Chrome's behavior of keeping transactions alive across promise resolutions. Otherwise, you can't do much with promises and IDB.

Since the interaction between transactions and promises is not explicitly specified anywhere, and there is some debate as to what behavior is actually correct, I don't have much faith that it'll be easy to get cross-browser consensus. Given those circumstances, an explicit spec like this would be a huge step forward.

**Comment by wanderview** [comment]
FWIW I think we should still consider a promise based IDB API for a few reasons:

1. We are moving to the use of promises in more APIs.  For example, there is a desire to add promise support for document load in whatwg/html#1936.

2. Async functions (now in all modern browsers) make promise based APIs significantly easier to use.

3. There is a perf and maintenance advantage to reducing libraries.  Yes, some libraries will still be needed for interop with old browsers, but it would be nice not to require one for a sane API in something like a service worker script where you know you have a modern browser.

CC some of our IDB folks: @bevis-tseng @asutherland.

**Comment by inexorabletash** [comment]
Someone else taking the initiative here would be awesome. I'm obviously coming at the problem from a biased perspective (as implementer, editor, and thus someone intimately familiar with the existing API). I also totally agree with the observation by @indolering - the current proposal is bolting Promises on to IDB, not designing a clean ergonomic API with the same functionality.

**Comment by nolanlawson** [comment]
I agree with @wanderview's points. I think maybe a brand-new API designed from scratch with Promises in mind may be the best way forward here.

The main upside is that we'd have a cleaner IndexedDB API for a world of Promises and async functions. The downside is that it wouldn't be polyfillable on top of the old API (due to inability to pause transactions for Promise resolution, as well as how microtasks are treated in non-Blink browsers).

OTOH the polyfill issue may be a minor one. For use cases like simple key-value stores it should be polyfillable.

**Comment by jakearchibald** [comment]
(the microtask thing seems fixed in all browsers but Firefox, and they're actively working on it)

**Comment by nolanlawson** [comment]
@jakearchibald lol I was just about to post this. 🙃

Went back and wrote a quick test case, and yeah Safari 11, Edge 16, and Chrome 63 all seem to have the same behavior:
- [Test 1](https://bl.ocks.org/nolanlawson/raw/04e1a13863d10994dce1d5562b3dffed/)
- [Test 2](https://bl.ocks.org/nolanlawson/raw/776c250eb0f1723a83bd782fde55ef8f/)

Firefox Dev Edition 59 is the odd one out. Glad to know they're working on it!

**Comment by inexorabletash** [comment]
Resolving this (well, the _"My proposal: IndexedDB needs a "simple" API for folks who miss localStorage"_ part) in favor of https://github.com/domenic/async-local-storage/
