### ISSUE TITLE
Promise associated with cursors?

### ISSUE THREAD

**Issue by inexorabletash** [inexorabletash/indexeddb-promises#5]
In email to public-webapps, @domenic suggests "For cursors, I'd suggest something like `.next` or `.nextReady` or similar."

I'm not entirely sure how that would be used with the current API. If the semantics were that the promise rejected when the cursor finished, it could be used as:

``` js
let cursor = await store.openCursor().promise;
if (cursor) {
  while (await cursor.nextReady) {
    doSomethingWith(cursor.key, cursor.value);
    cursor.continue();
  }
}
```

rather than:

``` js
let cursor = await store.openCursor().promise;
while (cursor) {
    doSomethingWith(cursor.key, cursor.value);
    cursor = await cursor.continue().promise;
}
```

@domenic - is that what you were envisioning?

**Comment by domenic** [comment]
> If the semantics were that the promise rejected when the cursor finished

I guess by the example you mean fulfilled with false? Interesting, and not bad...

I was actually just saying that instead of `cursor = await cursor.continue().promise`, you could do `cursor = await cursor.continue().next`.

Really this all wants [async iterators](https://github.com/zenparsing/async-iteration/), but, blocking on ES is never good.

**Comment by inexorabletash** [comment]
Ah. Well, right now `cursor.continue()` returns nothing (void). The proposal has it return the IDBRequest associated with the cursor. So by default that would get `.promise` or whatever we come up with in #4, or we could make up a new return value. But just ensuring we get something acceptable in #4 probably covers it.

**Comment by inexorabletash** [comment]
So this ends up being:

``` js
cursor = await cursor.continue().ready;
```

... which I think satisfies what @domenic was going for.
